package fr.insalyon.tc.raft;

import java.io.Serializable;
import java.util.UUID;

/**
 * Represent a Heartbeat generated by a sender
 */
@SuppressWarnings("WeakerAccess")
public class Heartbeat implements Serializable{
    public final String id = UUID.randomUUID().toString();
    public final String senderId;
    public final long time = System.currentTimeMillis();

    public Heartbeat(Node sender){
        senderId = sender.getId();
    }
}
